name: UI Tests
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
      - name: Run UI Tests
        run: mvn clean test
